name: Auto Tests

on:
  push:
    branches:
      - main  # Adjust the branch name as needed
  pull_request:
    branches:
      - main  # Adjust the branch name as needed
  schedule:
    - cron: "*/10 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Enable Git tracing
        run: |
          echo "GIT_TRACE=1" >> $GITHUB_ENV

      - name: Checkout code
        env:
          GIT_TRACE: "1"
        run: |
          git clone https://github.com/Arty781/Yugo.git

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'  # Adjust the .NET version as needed

      - name: Restore dependencies
        run: dotnet restore yugo.sln

      - name: Build solution
        run: dotnet build yugo.sln --configuration Release

      - name: Run tests
        run: dotnet test yugo.sln --configuration Release --logger "trx;LogFileName=testresults.trx"
