name: Auto Tests

on:
  push:
    branches:
      - master  # Adjust the branch name as needed
  pull_request:
    branches:
      - master  # Adjust the branch name as needed
  schedule:
    - cron: "0 */13 * * *"

jobs:
  test:
    runs-on: windows-latest

    steps:
     # - name: Enable Git tracing
     #   run: |
     #     echo "GIT_TRACE=1" >> $GITHUB_ENV
      - uses: actions/checkout@v3    
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x  # Adjust the .NET version as needed
          
     # - name: Checkout code
     #   env:
     #     GIT_TRACE: "1"
     #   run: |
          # git clone https://github.com/Arty781/Yugo.git
          # Alternatively, use the PAT for authentication
     #     git clone https://$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@github.com/Arty781/Yugo.git

      #- name: Setup Node.js
      #  uses: actions/setup-node@v2
      #  with:
      #    node-version: '16.x'
      
      - name: Restore dependencies
        run: dotnet restore

      - name: Build and run tests
        run: |
          dotnet build --configuration Release --no-restore
          dotnet test --configuration Release  --no-restore --filter FullyQualifiedName~Template_Test.Yugo
