name: Auto Tests

on:
 # push:
 #   branches:
 #     - master  # Adjust the branch name as needed
  pull_request:
    branches:
      - master  # Adjust the branch name as needed
  schedule:
    - cron: "0 0,12 * * *"

jobs:
  test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3    
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x  # Adjust the .NET version as needed
      
      - name: Restore dependencies
        run: dotnet restore

      - name: Build and run tests
        run: |
          dotnet build --configuration Release --no-restore
          dotnet test --configuration Release  --no-restore --filter FullyQualifiedName~Template_Test.Yugo
